### ISSUE TITLE
Maintaining the package

### ISSUE THREAD

**Issue by aifreedom** [aifreedom/balena-homebridge#100]
Hi @rhwood , thank you for starting this project! I learned from your README that you are not going to maintain this package going forward. I've forked it at https://github.com/aifreedom/balena-homebridge/, made some changes and keep the packages (mostly homebridge and homebridge-config-ui-x) up-to-date. I'll continue to maintain this package.

**Comment by rhwood** [comment]
@aifreedom Once you rename your fork and notify me of that, I can transfer this repo to you (GitHub won't let me transfer it because your fork has the same name as this repo).

**Comment by aifreedom** [comment]
Just renamed it

**Comment by rhwood** [comment]
I am getting the error message

> aifreedom already has a repository in the rhwood/balena-homebridge network

I found [Prerequisites for repository transfers](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository):

> - When you transfer a repository that you own to another user account, the new owner will receive a confirmation email. The confirmation email includes instructions for accepting the transfer. If the new owner doesn't accept the transfer within one day, the invitation will expire.
> - To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.
> - The target account must not have a repository with the same name, or a fork in the same network.
> - The original owner of the repository is added as a collaborator on the transferred repository. Other collaborators to the transferred repository remain intact.
> - Private forks can't be transferred.

So it looks like renaming your fork won't work.

I have merged in all your changes into this repo in #101.

If you're comfortable taking over this repo in this state, delete your fork and I'll transfer it. Please let me know either way.

**Comment by aifreedom** [comment]
I have deleted my fork. You can try transfer it one more time.
